### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by downthecrop** [downthecrop/2009Scape-mobile#1]
- [ ] mouse cursor size
- [ ] focus keyboard button when typing
- [ ] long press dragging
- [ ] ' :' key doesn't work

**Comment by downthecrop** [comment]
about sound: The JVM doesn't seem to have a sound device active. LWJGL uses OpenAL for audio which is implemented as this is what minecraft uses for sound. Assuming I'm correct piping the sound into a OpenAL Audio Buffer would make this work.

**Comment by downthecrop** [comment]
![Screenshot_20220206-004323](https://user-images.githubusercontent.com/4764745/152747711-ba177fda-02da-404d-8477-301f05c82974.png)

**Comment by downthecrop** [comment]
Sound demo https://www.youtube.com/watch?v=Ud_2D6gFY6M
miniclient update: https://github.com/downthecrop/miniclient/commit/8df85a870ccd6eb4a21e232e58017d99c238d884

**Comment by broskinem15** [comment]
hey can you make it so the dragging and clicking aren't messed up

**Comment by downthecrop** [comment]
UI suggestions

![IMG_7547](https://user-images.githubusercontent.com/4764745/191526306-a3afc373-7893-4507-a1c7-4c42e4eecdb6.png)
Counterstrike 

![IMG_7548](https://user-images.githubusercontent.com/4764745/191526251-47216518-5ea0-498e-94fe-dd02b4de5748.png)

**Comment by broskinem15** [comment]
that's not on my mobile how do I get that to the left
